// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZurwI-Bw5n3OhhOkegQtuNRN4gVSeR6w',
    appId: '1:934365838420:web:9834b4a50a9200675d81c1',
    messagingSenderId: '934365838420',
    projectId: 'kickmyflutterfirejoyce',
    authDomain: 'kickmyflutterfirejoyce.firebaseapp.com',
    storageBucket: 'kickmyflutterfirejoyce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzlK0kXzwIzJnUynB_sb0A93dIaCcpZPk',
    appId: '1:934365838420:android:eecde76295e112175d81c1',
    messagingSenderId: '934365838420',
    projectId: 'kickmyflutterfirejoyce',
    storageBucket: 'kickmyflutterfirejoyce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqtDLN04fM1c_IO0M2c8dHPx5GFcW7Elo',
    appId: '1:934365838420:ios:214c260d8aa1e52b5d81c1',
    messagingSenderId: '934365838420',
    projectId: 'kickmyflutterfirejoyce',
    storageBucket: 'kickmyflutterfirejoyce.appspot.com',
    iosClientId: '934365838420-gfppe2ab52ff5g9qblqbaiufbrig16fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqtDLN04fM1c_IO0M2c8dHPx5GFcW7Elo',
    appId: '1:934365838420:ios:214c260d8aa1e52b5d81c1',
    messagingSenderId: '934365838420',
    projectId: 'kickmyflutterfirejoyce',
    storageBucket: 'kickmyflutterfirejoyce.appspot.com',
    iosClientId: '934365838420-gfppe2ab52ff5g9qblqbaiufbrig16fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
